### ISSUE TITLE
Modules Not Parsed likely due to needing some permission to talk to Terraform Cloud

### ISSUE THREAD

**Issue by sheldonhull** [patrickjahns/dependabot-terraform-action#18]
```
Fetching terraform dependency files for myorg/reponame
Parsing dependencies information
bundler: failed to load command: ./dependabot.rb (./dependabot.rb)
KeyError: key not found: "module_calls"
```

This issue occurred on the latest run.
I'm wondering how I should provide the terraform cloud authentication token to this job since I believe that is what likely triggered this failure.
I am using Terraform Cloud as the module provider for many of my modules and am assuming that this authentication is likely the failure as it needs to communicate with Terraform Cloud which then uses Github app connection to pull modules.  Any ideas?

**Comment by patrickjahns** [comment]
Would you be able to provide a short example terraform code that fails for you? 
Is this a public or private terraform cloud module ?

**Comment by patrickjahns** [comment]
Should be addressed in https://github.com/patrickjahns/dependabot-terraform-action/pull/19
